name: Deploy Astro Site

on:
  push:
    branches:
      - master # This workflow runs every a push to the master branch occurs
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache Astro Build
        id: cache-astro
        uses: actions/cache@v4
        with:
          path: .astro/cache
          key: astro-build-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            astro-build-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        run: npm run build

      - name: Cache dist directory
        uses: actions/cache@v.4
        with:
          path: dist
          key: dist-cache-${{ github.sha }} # Keyed to the exact commit
  
  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Restore dist directory from cache
        uses: actions/cache@v4
        with:
          path: dist
          key: dist-cache-${{ github.sha }} # Use the exact same key to restore

      - name: Deploy with Rsync
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          REMOTE_PORT: ${{ secrets.PORT }} 
          TARGET_DIR: ${{ secrets.REMOTE_PATH }}
        run: |
          echo "$SSH_PRIVATE_KEY" > deploy_key
          chmod 600 deploy_key

          SSH_CMD="ssh -i ./deploy_key -p $REMOTE_PORT -o StrictHostKeyChecking=no"
          
          rsync -rlgoDzvc --delete \
            -e "$SSH_CMD" \
            --rsync-path=/usr/bin/rsync \
            ./dist/ \
            $REMOTE_USER@$REMOTE_HOST:$TARGET_DIR